# typings/vllm/__init__.pyi
class LLM:
    def __init__(self, model: str, tensor_parallel_size: int): ...
    def generate(self, prompts: list, sampling_params: object) -> list: ...

class SamplingParams:
    def __init__(self, temperature: float): ...